import {useState} from "react";
import {MemoryStick,ShieldAlert,FileCheck2,Download,FolderSearch,FileArchive,CheckCircle2,ChevronRight,RefreshCw} from "lucide-react";
type Log={name:string;path:string;size_bytes:number;sha256:string;format:string;detection?:{classification:string;format_name:string;confidence:string}};
const steps=["Выбор SD","Форматирование","Профиль","Запись","Установка","Контрольный лог"];
export default function OpenPortSDPrep(){
 const [cfg,setCfg]=useState(""),[profiles,setProfiles]=useState<any[]>([]),[profile,setProfile]=useState<any>(null),[status,setStatus]=useState<any>(null),[folder,setFolder]=useState(""),[logs,setLogs]=useState<Log[]>([]),[imported,setImported]=useState<any>(null),[drives,setDrives]=useState<any[]>([]),[tab,setTab]=useState<"wizard"|"import">("wizard"),[step,setStep]=useState(0),[target,setTarget]=useState<any>(null),[written,setWritten]=useState<any>(null),[error,setError]=useState("");
 const detect=async()=>{setError("");const r=await fetch("/api/capture/openport-sd/drives");if(r.ok){const x=await r.json();setDrives(x);if(x.length===1){setFolder(x[0].root);await inspect(x[0].root)}}};
 const inspect=async(root=folder)=>{if(!root)return;const r=await fetch("/api/capture/openport-sd/prepare/inspect?"+new URLSearchParams({root}));const x=await r.json();if(!r.ok){setError(x.detail||"SD check failed");return}setTarget(x);setFolder(root)};
 const loadProfiles=async()=>{const r=await fetch("/api/capture/openport-sd/profiles");if(r.ok)setProfiles(await r.json())};
 const chooseProfile=async(id:string)=>{const r=await fetch("/api/capture/openport-sd/profiles/"+id);if(!r.ok)return;const x=await r.json();setProfile(x);setCfg(x.content||"");setStatus({status:x.status,mode:x.mode,warning:x.warning});};
 const generate=async()=>{await loadProfiles();setStep(2)};
 const validate=async()=>{const q=new URLSearchParams({text:cfg,filename:"logcfg.txt"});const r=await fetch("/api/capture/openport-sd/validate?"+q,{method:"POST"});const x=await r.json();setStatus(x);return x.valid};
 const write=async()=>{setError("");if(!await validate()){setError("Конфигурация не прошла проверку.");return}const q=new URLSearchParams({root:folder,text:cfg});const r=await fetch("/api/capture/openport-sd/prepare/write?"+q,{method:"POST"});const x=await r.json();if(!r.ok){setError(typeof x.detail==="string"?x.detail:JSON.stringify(x.detail));return}setWritten(x);setStep(4)};
 const save=()=>{const b=new Blob([cfg],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="logcfg.txt";a.click();URL.revokeObjectURL(a.href)};
 const scan=async()=>{const r=await fetch("/api/capture/openport-sd/logs?"+new URLSearchParams({folder}));setLogs(r.ok?await r.json():[])};
 const imp=async(p:string)=>{const r=await fetch("/api/capture/openport-sd/import?"+new URLSearchParams({path:p}),{method:"POST"});if(r.ok)setImported(await r.json())};
 return <section className="panel sdPrep"><div className="pt"><div><MemoryStick/><b>OpenPort SD · автономная запись</b></div><span>GUIDED · NON-DESTRUCTIVE</span></div>
 <div className="sdTabs"><button className={tab==="wizard"?"active":""} onClick={()=>setTab("wizard")}>МАСТЕР ПОДГОТОВКИ</button><button className={tab==="import"?"active":""} onClick={()=>setTab("import")}>ИМПОРТ ЛОГОВ</button></div>
 {tab==="wizard"?<><div className="wizardRail">{steps.map((x,i)=><div className={i<step?"done":i===step?"current":""} key={x}><span>{i<step?"✓":i+1}</span><b>{x}</b></div>)}</div>
 <div className="sdNotice"><ShieldAlert/><div><b>SherloCAN не форматирует диски</b><p>Форматирование выполняется пользователем средствами Windows. Мастер только определяет выбранный накопитель, показывает инструкцию и после этого повторно проверяет цель.</p></div></div>
 {step===0&&<div className="wizardCard"><h3>1. Подключите microSD к компьютеру</h3><p>Нажмите «Найти SD», затем обязательно сверьте букву накопителя перед продолжением.</p><button onClick={detect}><FolderSearch/>НАЙТИ SD</button>{drives.map((d,i)=><button className="driveChoice" key={i} onClick={()=>{setFolder(d.root);inspect(d.root)}}><b>{d.root}</b><span>{d.candidate_reason}</span></button>)}{target?.safe_target&&<><div className="targetConfirm"><CheckCircle2/><b>{target.root}</b><span>{(target.size_bytes/1073741824).toFixed(2)} GB · non-system target</span></div><button onClick={()=>setStep(1)}>ЭТО МОЯ microSD <ChevronRight/></button></>}</div>}
 {step===1&&<div className="wizardCard"><h3>2. Отформатируйте выбранную карту в Windows</h3><div className="formatTarget"><b>ЦЕЛЬ: {target?.root}</b><span>Рекомендуемая ФС: FAT32 · метка: SHERLOCAN</span></div><ol>{target?.formatting?.windows_steps?.map((x:string)=><li key={x}>{x}</li>)}</ol><p className="dangerNote">Перед нажатием Format ещё раз убедитесь, что в Windows выбрана именно {target?.root}. Форматирование удалит файлы на этой карте.</p><button onClick={async()=>{await inspect(folder);setStep(2)}}><RefreshCw/>Я ЗАВЕРШИЛ ФОРМАТИРОВАНИЕ · ПРОВЕРИТЬ</button></div>}
 {step===2&&<div className="wizardCard"><h3>3. Создайте профиль автономного логирования</h3><p>Текущий встроенный шаблон — активный OBD/ISO15765 профиль RPM / Speed / Coolant. Он отправляет диагностические запросы и не является passive RAW CAN.</p>{profiles.length===0?<button onClick={generate}>ПОКАЗАТЬ ПРОФИЛИ</button>:<div className="profileGrid">{profiles.map((p:any)=><button key={p.id} className={profile?.id===p.id?"selected":""} onClick={()=>chooseProfile(p.id)}><b>{p.name}</b><span>{p.description}</span><i>{p.status}</i></button>)}</div>}{profile&&<div className={"profileState "+profile.status}><b>{profile.name} · {profile.status}</b><span>{profile.warning||profile.description}</span></div>}{profile&&<>{(profile.editable||cfg)&&<textarea value={cfg} onChange={e=>setCfg(e.target.value)} placeholder="Вставьте проверенный logcfg.txt…"/>}<div className="sdActions"><button onClick={validate}><FileCheck2/>ПРОВЕРИТЬ</button><button onClick={save}><Download/>КОПИЯ НА ПК</button><button onClick={()=>setStep(3)} disabled={!cfg}>ПРОДОЛЖИТЬ <ChevronRight/></button></div></>}</div>}
 {step===3&&<div className="wizardCard"><h3>4. Запишите и проверьте logcfg.txt</h3><p>SherloCAN запишет только конфигурацию и служебный manifest на уже выбранную карту {folder}. После записи файл читается обратно и сравнивается.</p><button onClick={write} disabled={!cfg}><FileCheck2/>ЗАПИСАТЬ И ПРОВЕРИТЬ</button>{status&&<pre>{JSON.stringify(status,null,2)}</pre>}</div>}
 {step===4&&<div className="wizardCard"><h3>5. Безопасно извлеките карту и установите в OpenPort</h3>{written&&<div className="targetConfirm"><CheckCircle2/><b>logcfg.txt VERIFIED</b><span>{written.config_path}</span></div>}<ol><li>Закройте приложения, использующие карту.</li><li>В Windows выполните «Извлечь» для {folder} и дождитесь разрешения.</li><li>Отсоедините microSD от компьютера.</li><li>Вставьте microSD в OpenPort 2.0 до подключения интерфейса к автомобилю.</li><li>Подключите OpenPort к OBD-II автомобиля.</li></ol><button onClick={()=>setStep(5)}>КАРТА УСТАНОВЛЕНА <ChevronRight/></button></div>}
 {step===5&&<div className="wizardCard"><h3>6. Выполните короткий контрольный лог</h3><ol><li>Включите зажигание в состоянии, предусмотренном вашим сценарием.</li><li>Оставьте OpenPort подключённым на короткий контрольный интервал.</li><li>Завершите тест, отключите OpenPort и извлеките microSD.</li><li>Верните карту в компьютер и откройте вкладку «Импорт логов».</li></ol><button onClick={()=>setTab("import")}>ПЕРЕЙТИ К ИМПОРТУ ЛОГА <ChevronRight/></button></div>}{error&&<div className="analysisError"><ShieldAlert/>{error}</div>}</>:
 <><div className="sdImportHero"><div><FolderSearch/><div><b>Импорт автономных логов в Evidence</b><p>Подключите microSD после контрольной поездки. Исходный лог не изменяется: создаётся evidence-copy и SHA-256.</p></div></div><div className="sdFolder"><button onClick={detect}><FolderSearch/>НАЙТИ SD</button><input value={folder} onChange={e=>setFolder(e.target.value)} placeholder={"Например: E:\\"}/><button onClick={scan} disabled={!folder}><FolderSearch/>СКАНИРОВАТЬ</button></div></div><div className="sdLogList">{logs.length===0?<div className="sdEmpty">Логи ещё не обнаружены.</div>:logs.map(x=><div className="sdLog" key={x.path}><FileArchive/><div><b>{x.name}</b><span>{x.format.toUpperCase()} · {(x.size_bytes/1024).toFixed(1)} KB · {x.detection?.classification||"UNKNOWN"}</span><code>SHA-256 {x.sha256.slice(0,20)}…</code></div><button onClick={()=>imp(x.path)}>IMPORT → EVIDENCE</button></div>)}</div>{imported&&<div className="sdImported"><CheckCircle2/><div><b>Evidence copy создана</b><span>{imported.session_id}</span><code>{imported.sha256}</code></div></div>}</>}
 </section>
}